export interface Migration {
  tag: string;
  statements: string[];
}

/** Reads the drizzle-kit journal and SQL files (through `read`) into ordered migrations. */
export function readMigrations(read: (file: string) => string): Migration[] {
  const journal = JSON.parse(read('meta/_journal.json')) as {
    entries: { idx: number; tag: string }[];
  };
  return [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map(({ tag }) => ({
      tag,
      statements: read(`${tag}.sql`)
        .split('--> statement-breakpoint')
        .map((s) => s.trim())
        .filter(Boolean),
    }));
}

/** Source of `migrations.generated.ts`. */
export function bundleMigrations(read: (file: string) => string): string {
  return (
    '// Generated by scripts/build-migrations.ts from packages/db/drizzle. Do not edit.\n' +
    "import type { Migration } from './migrations-bundle';\n\n" +
    `export const migrations: Migration[] = ${JSON.stringify(readMigrations(read), null, 2)};\n`
  );
}
