// Generated by scripts/build-migrations.ts from packages/db/drizzle. Do not edit.
import type { Migration } from './migrations-bundle';

export const migrations: Migration[] = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE `attempt` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`node_id` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`result` text NOT NULL,\n\t`played_uci` text,\n\t`hints` integer DEFAULT 0 NOT NULL,\n\t`time_ms` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `session`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`node_id`) REFERENCES `node`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"attempt_result_check\" CHECK(\"attempt\".\"result\" in ('correct','hint','wrong'))\n);",
      "CREATE INDEX `attempt_node_ts_idx` ON `attempt` (`node_id`,`ts`);",
      "CREATE INDEX `attempt_session_idx` ON `attempt` (`session_id`);",
      "CREATE TABLE `card` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`node_id` text NOT NULL,\n\t`due` integer NOT NULL,\n\t`stability` real DEFAULT 0 NOT NULL,\n\t`difficulty` real DEFAULT 0 NOT NULL,\n\t`elapsed_days` integer DEFAULT 0 NOT NULL,\n\t`scheduled_days` integer DEFAULT 0 NOT NULL,\n\t`learning_steps` integer DEFAULT 0 NOT NULL,\n\t`reps` integer DEFAULT 0 NOT NULL,\n\t`lapses` integer DEFAULT 0 NOT NULL,\n\t`state` integer DEFAULT 0 NOT NULL,\n\t`last_review` integer,\n\tFOREIGN KEY (`node_id`) REFERENCES `node`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `card_node_id_unique` ON `card` (`node_id`);",
      "CREATE TABLE `collection` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`start_fen` text NOT NULL,\n\t`user_color` text NOT NULL,\n\t`eval_mode` text NOT NULL,\n\t`source` text,\n\t`license` text,\n\t`created_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL,\n\tCONSTRAINT \"collection_kind_check\" CHECK(\"collection\".\"kind\" in ('opening','game','mate','pattern','endgame')),\n\tCONSTRAINT \"collection_user_color_check\" CHECK(\"collection\".\"user_color\" in ('w','b')),\n\tCONSTRAINT \"collection_eval_mode_check\" CHECK(\"collection\".\"eval_mode\" in ('exact','result'))\n);",
      "CREATE TABLE `daily_stat` (\n\t`day` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`scope_key` text NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`correct` integer DEFAULT 0 NOT NULL,\n\t`hint` integer DEFAULT 0 NOT NULL,\n\t`wrong` integer DEFAULT 0 NOT NULL,\n\t`new_cards` integer DEFAULT 0 NOT NULL,\n\t`time_ms` integer DEFAULT 0 NOT NULL,\n\tPRIMARY KEY(`day`, `scope`, `scope_key`),\n\tCONSTRAINT \"daily_stat_scope_check\" CHECK(\"daily_stat\".\"scope\" in ('collection','kind'))\n);",
      "CREATE TABLE `node` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`collection_id` text NOT NULL,\n\t`parent_id` text,\n\t`ord` integer DEFAULT 0 NOT NULL,\n\t`epd` text NOT NULL,\n\t`san` text,\n\t`uci` text,\n\t`is_user_move` integer DEFAULT false NOT NULL,\n\t`comment` text,\n\t`opening_eco` text,\n\t`opening_name` text,\n\tFOREIGN KEY (`collection_id`) REFERENCES `collection`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`parent_id`) REFERENCES `node`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"node_move_check\" CHECK((\"node\".\"parent_id\" is null) = (\"node\".\"uci\" is null))\n);",
      "CREATE INDEX `node_epd_idx` ON `node` (`epd`);",
      "CREATE INDEX `node_collection_idx` ON `node` (`collection_id`);",
      "CREATE INDEX `node_parent_idx` ON `node` (`parent_id`);",
      "CREATE TABLE `opening` (\n\t`epd` text PRIMARY KEY NOT NULL,\n\t`eco` text NOT NULL,\n\t`name` text NOT NULL,\n\t`family` text NOT NULL,\n\t`variation` text,\n\t`uci` text NOT NULL,\n\t`ply` integer NOT NULL\n);",
      "CREATE INDEX `opening_eco_idx` ON `opening` (`eco`);",
      "CREATE UNIQUE INDEX `opening_uci_idx` ON `opening` (`uci`);",
      "CREATE TABLE `session` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`collection_id` text NOT NULL,\n\t`root_node_id` text NOT NULL,\n\t`started_at` integer NOT NULL,\n\t`ended_at` integer,\n\tFOREIGN KEY (`collection_id`) REFERENCES `collection`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`root_node_id`) REFERENCES `node`(`id`) ON UPDATE no action ON DELETE no action\n);"
    ]
  },
  {
    "tag": "0001_archive_and_line_pass",
    "statements": [
      "CREATE TABLE `line_pass` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`collection_id` text NOT NULL,\n\t`line_id` text NOT NULL,\n\t`clean` integer NOT NULL,\n\t`diverged` integer NOT NULL,\n\t`ts` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `session`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`collection_id`) REFERENCES `collection`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `line_pass_collection_ts_idx` ON `line_pass` (`collection_id`,`ts`);",
      "DROP INDEX `opening_uci_idx`;",
      "ALTER TABLE `opening` DROP COLUMN `uci`;",
      "ALTER TABLE `opening` DROP COLUMN `ply`;",
      "ALTER TABLE `collection` ADD `archived_at` integer;"
    ]
  },
  {
    "tag": "0002_opening_lab",
    "statements": [
      "CREATE TABLE `lab_attempt` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`run_id` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`epd` text NOT NULL,\n\t`uci` text NOT NULL,\n\t`ply` integer NOT NULL,\n\t`result` text NOT NULL,\n\t`played_uci` text NOT NULL,\n\t`hints` integer DEFAULT 0 NOT NULL,\n\t`time_ms` integer NOT NULL,\n\tCONSTRAINT \"lab_attempt_result_check\" CHECK(\"lab_attempt\".\"result\" in ('correct','hint','wrong'))\n);",
      "CREATE INDEX `lab_attempt_edge_ts_idx` ON `lab_attempt` (`epd`,`uci`,`ts`);",
      "CREATE TABLE `lab_run` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`ts` integer NOT NULL,\n\t`line` text NOT NULL,\n\t`eco` text,\n\t`name` text,\n\t`plies` integer NOT NULL,\n\t`errors` integer NOT NULL,\n\t`hints` integer NOT NULL,\n\t`clean` integer NOT NULL,\n\t`time_ms` integer NOT NULL\n);",
      "CREATE INDEX `lab_run_line_ts_idx` ON `lab_run` (`line`,`ts`);"
    ]
  }
];
